#!/usr/bin/python3

import random

def name_fortune(name):
    fortunes = [
        "Great things are coming your way!",
        "Today is your lucky day!",
        "Challenges ahead, but you can overcome them!",
        "Expect some good news soon!",
        "You will find happiness in unexpected places."
    ]
    return f"{name}, your fortune is: {random.choice(fortunes)}"

user_name = input("Enter your name: ")
print(name_fortune(user_name))
